### ISSUE TITLE
error during sampling

### ISSUE THREAD

**Issue by zhouxiangxin1998** [zaixizhang/FLAG#1]
During sampling, once the exception of UFF is triggered, an error will come from this line (https://github.com/zaixizhang/FLAG/blob/main/motif_sample.py#L295), and the program will exit.
```
ValueError: Bad Conformer Id
```
Could you give some explanations or suggestions to address this?

**Comment by zhouxiangxin1998** [comment]
There is another concern here:
If the exception of UFF is triggered (which means generating conformation by RDKit is failed), this sample is supposed to be skipped. Because the conformation is messy, not reliable, thus not suitable to be involved in the later sampling procedure. However, it seems that this sample is not skipped according to the code.
  
I'll appreciate it if you can leave some helpful messages about this.

**Comment by zaixizhang** [comment]
Thanks for your feedback!
The UFF error is caused by the rdkit function. You can use different seeds to skip the triggered error. We will optimize our code in future versions.

**Comment by yangzhao1230** [comment]
Hi,

I have tried more than ten random seeds, but I still encounter this error. Is this normal?
