### ISSUE TITLE
how to build the dataset 

### ISSUE THREAD

**Issue by yuwang-langrui** [zaixizhang/FLAG#10]
hi, thank you for nice work.
May i know how you build the dataset files like pdbbind_pocket10_xxx
Would you please share your code?

**Comment by elana-caire** [comment]
hello, I tried running the code but there were issues with absent inputs, would it be possible to know how you built your input files ? (split_by_name.pt, index.pt, crossdocked_pocket10_name2id, crossdocked_pocket10_name2id.pt, crossdocked_pocket10_processed.lmdb) also one file refers to dataset pdbbind_pocket10 (sample.yml) and the others refer to crossdocked_pocket10 (train_model.yml, pl.py,mol_tree.py) but on the drive only crossdocked_pocket10  is available ?

**Comment by ZhuJiwei111** [comment]
Yes, I am also confused about this. And I try to use crossdocked_pocket10 to train, but there is a error that the index in the folder is a pkl file rather than a pt file. When I opened index, I found that pybid was a tuple, but you used the join to get the path.[](https://github.com/zaixizhang/FLAG/blob/44ba5fd2a2ec70b56362ee7093e64ebc9c4a13d0/utils/datasets/pl.py#L112C36-L112C40)
 Would you please share your more details?

**Comment by MachineGUN001** [comment]
when I run the train.py, the error occured.

```
Traceback (most recent call last):
  File "e:\FLAG-main\train.py", line 63, in <module>
    dataset, subsets = get_dataset(config=config.dataset, transform=transform, )
  File "e:\FLAG-main\utils\datasets\__init__.py", line 11, in get_dataset
    dataset = PocketLigandPairDataset(root, *args, **kwargs)
  File "e:\FLAG-main\utils\datasets\pl.py", line 66, in __init__
    self.name2id = torch.load(self.name2id_path)
  File "c:\.conda\envs\diffhopp\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "c:\.conda\envs\diffhopp\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "c:\.conda\envs\diffhopp\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data\\crossdocked_pocket10_name2id.pt'
```

could you please provide this `crossdocked_pocket10_name2id.pt` file? 

many thanks,

**Comment by FeilongWuHaa** [comment]
"crossdocked_pocket10_name2id.pt" is a processed file during the model training. you can delete the "crossdocked_pocket10_processed.lmdb" and "crossdocked_pocket10_processed.lmdb-lock" in ./data, and run "python train.py" again, "crossdocked_pocket10_name2id.pt" will be generated.

**Comment by MachineGUN001** [comment]
> "crossdocked_pocket10_name2id.pt" is a processed file during the model training. you can delete the "crossdocked_pocket10_processed.lmdb" and "crossdocked_pocket10_processed.lmdb-lock" in ./data, and run "python train.py" again, "crossdocked_pocket10_name2id.pt" will be generated.

thanks for your help. that works!

**Comment by zaixizhang** [comment]
It seems the issue is well solved. Thanks!

**Comment by sxy759334746** [comment]
> hello, I tried running the code but there were issues with absent inputs, would it be possible to know how you built your input files ? (split_by_name.pt, index.pt, crossdocked_pocket10_name2id, crossdocked_pocket10_name2id.pt, crossdocked_pocket10_processed.lmdb) also one file refers to dataset pdbbind_pocket10 (sample.yml) and the others refer to crossdocked_pocket10 (train_model.yml, pl.py,mol_tree.py) but on the drive only crossdocked_pocket10 is available ?

Hello do you solved this problem? @soraya-rey

**Comment by sxy759334746** [comment]
> Yes, I am also confused about this. And I try to use crossdocked_pocket10 to train, but there is a error that the index in the folder is a pkl file rather than a pt file. When I opened index, I found that pybid was a tuple, but you used the join to get the path. Would you please share your more details?
@ZhuJiwei111  Do you sloved this problem?

**Comment by sxy759334746** [comment]
@FeilongWuHaa  I have some problems about how do i get the index.pt which is required in getdataset?

```
class PocketLigandPairDataset(Dataset):
    def __init__(self, raw_path, transform=None):
        super().__init__()
        self.raw_path = raw_path.rstrip('/')
        self.index_path = os.path.join(self.raw_path, 'index.pt')
```

I only see the index.pkl in ./data/crossdocked_pocket10. I download ont index.pt from [](https://drive.google.com/drive/folders/1NI-Tl7YzyMsfljEZXaTxbpuiO7lvUBt9). Then all sdf files were skipped.

`100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16226/16226 [00:00<00:00, 159945.42it/s]
Indexing: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    train_iterator = inf_iterator(DataLoader(train_set, batch_size=config.train.batch_size,
  File "/home/students/xiaoyang22/miniconda3/envs/flag_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/home/students/xiaoyang22/miniconda3/envs/flag_env/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
`
I need help!!
