### ISSUE TITLE
Sampling Code Not Working

### ISSUE THREAD

**Issue by Franco-Solis** [zaixizhang/FLAG#2]
We are trying to reproduce the results from the original FLAG paper. We have been able to tweak the training code to make it work, but we still bump into some knotty issues during the sampling/generation stage. Following the original instructions from `README.md`, we start the sampling process by running the following command: 

``` python
python motif_sample.py
```

The Python interpreter gives the following error: 

```python
Traceback (most recent call last):
  File "motif_sample.py", line 18, in <module>
    from models.maskfill import MaskFillModel
ModuleNotFoundError: No module named 'models.maskfill'
```

Then I came to realize: there is no such file as `./models/maskfill.py` in the Github repo. I googled for the file and found a file with the same name in the 3DSBDD repo (https://github.com/luost26/3D-Generative-SBDD/blob/main/models/maskfill.py). However, the class `__init__()` function arguments do not match. In `motif_sample.py:412`: 

```python
    model = MaskFillModel(
        ckpt['config'].model,
      	protein_atom_feature_dim=protein_featurizer.feature_dim,
        ligand_atom_feature_dim=ligand_featurizer.feature_dim,
        vocab=vocab,
        weight=weight,
    ).to(args.device)
```

The `vocab` and `weight` arguments are non-existent in the 3DSBDD version of  `maskfill.py`. I assume the FLAG authors have made substantial changes in the `maskfill.py` file, but happen not to upload it to Github. I cannot proceed with my experiment reproduction beyond this point before the FLAG version of  `maskfill.py` is uploaded.

**Comment by Franco-Solis** [comment]
Following the author's preliminary advice, we refactored the code to deprecate any reference to the `MaskFillModel` class, and use the `FLAG` class instead: 

```python
    from models.flag import FLAG
    # model = MaskFillModel(
    model = FLAG(
        ckpt['config'].model,
      	protein_atom_feature_dim=protein_featurizer.feature_dim,
        ligand_atom_feature_dim=ligand_featurizer.feature_dim,
        vocab=vocab,
        # weight=weight,
    ).to(args.device)
```

The `weight` argument is non-existent in the `FLAG` class definition in `./models/flag.py`, so I have to remove it to make the Python interpreter happy.  I executed the `motif_sample.py` again and was delighted to see the model parameters successfully loaded from my pre-trained model. However, it was not long before the interpreter exited with another error message: 

``` python
Traceback (most recent call last):
  File "motif_sample.py", line 435, in <module>
    gen_data, pos_list = ligand_gen(batch, model, vocab, config, center)
  File "motif_sample.py", line 177, in ligand_gen
    next_motif_wid, motif_prob = model.forward_motif(h_ctx_focal, current_wid,
ValueError: too many values to unpack (expected 2)
```

This error has arisen due to the fact that `forward_motif()` only returns one object `preds`, not two. The workaround I came up with was to deprecate any reference to the second alleged return value `motif_prob` around line 177: 

```python
# next_motif_wid, motif_prob = model.forward_motif(h_ctx_focal, current_wid,
next_motif_wid = model.forward_motif(h_ctx_focal, current_wid,
	torch.arange(config.sample.batch_size).to(h_ctx_focal.device))
# logp_motif = [[p] for p in np.log(motif_prob.cpu().numpy())] #init logp list

```

The code managed to move forward a few more steps, before another error emerged: 

```python
Traceback (most recent call last):
  File "motif_sample.py", line 435, in <module>
    gen_data, pos_list = ligand_gen(batch, model, vocab, config, center)
  File "motif_sample.py", line 226, in ligand_gen
    pos_list = refine_pos(torch.cat(pos_list, dim=0).float(), batch['protein_pos'].float(),
  File "motif_sample.py", line 109, in refine_pos
    alpha_index = batch['alpha_carbon_indicator'][protein_batch == i].nonzero().reshape(-1)
KeyError: 'alpha_carbon_indicator'
```

I searched through the whole repo for the keyword `'alpha_carbon_indicator'`, but did not find any clue about it. At this point, I have to come to realize that a substantial number of important source codes have been missing in the Github repo. 

I cannot proceed with the FLAG experiment reproduction beyond this point before the missing codes are updated to the repo. I hope my previous attempts to run the sampling code can give the authors some clue as to which part of codes are missing. Thank you so much.

**Comment by Samyu0304** [comment]
Also encounter this sampling issue when reproducing...

**Comment by zaixizhang** [comment]
Thanks for your feedback!
We have updated the corresponding codes to solve the aforementioned problems.
