### ISSUE TITLE
Can you provide your pre-trained model?

### ISSUE THREAD

**Issue by netblind** [zaixizhang/FLAG#4]
Hello author, thank you very much for your great work. May I ask if it is convenient for you to provide your pre-trained model? I saw in the sample.yml that it is the file "./pretrained/model.pt". If you could provide this trained model file, I would be very grateful. Thank you.

**Comment by zaixizhang** [comment]
Thanks for your interest in our work! We are optimizing the code and will provide the pre-trained model as soon as possible. Thanks!

**Comment by VincentBt** [comment]
Hi @zaixizhang, thanks for this fantastic work! I'm also interested in the model weights, it would be great if you could add them. Thank you in advance!

**Comment by qky18** [comment]
@zaixizhang Thanks for sharing your meaningful work! I'd like to follow it and thought it would be nice if there could be some model checkpoint provided. Thanks again!

**Comment by liguanlue** [comment]
Hello, I want to ask where is the pretrain model?

**Comment by zaixizhang** [comment]
Thanks for your interest and patience! Just uploaded the new version codes and checkpoints. Thanks!

**Comment by zaixizhang** [comment]
We also provide a huggingface demo: https://huggingface.co/spaces/Zaixi/ICLR_FLAG. It is based on the free CPU generation therefore it may take 1 minute to generate a batch of molecules. On GPU, it takes several seconds.
