### ISSUE TITLE
enum_assemble not found

### ISSUE THREAD

**Issue by netblind** [zaixizhang/FLAG#6]
The error "cands = enum_assemble(self, neighbors)" on line 91 of the mol_tree.py file in the utils folder is occurring because the method enum_assemble is not defined. I also did not find any import statement for this method. Could you please let me know where I can find this method? Thank you.

**Comment by OdinZhang** [comment]
> The error "cands = enum_assemble(self, neighbors)" on line 91 of the mol_tree.py file in the utils folder is occurring because the method enum_assemble is not defined. I also did not find any import statement for this method. Could you please let me know where I can find this method? Thank you.

Hi, I think the enum_assemble function is in the ./utils.chemutils

**Comment by VincentBt** [comment]
The function cannot be found anywhere in the code. @zaixizhang could you upload the function `enum_assemble`?

**Comment by zaixizhang** [comment]
The enum_assemble(self, neighbors) is not used in the generation. Therefore it is not incorporated in the code.
