### ISSUE TITLE
how to solve the processing data problem

### ISSUE THREAD

**Issue by zhangxiaofan-star** [zaixizhang/FLAG#7]
Hello author, thank you very much for your great work. When I run the file “train.py” and process data, there are often cases of skipping, skipping all data. Could you please give me a method to solve that？
![1687763877753](https://github.com/zaixizhang/FLAG/assets/130674437/08531d8f-5873-45ce-8046-000e47df06e7)

**Comment by zaixizhang** [comment]
Hi, Thanks for your interest in our work. Such errors may be brought by several reasons. It would be better to comment our the try and see exactly what caused the skipping.

**Comment by sxy759334746** [comment]
> Hello author, thank you very much for your great work. When I run the file “train.py” and process data, there are often cases of skipping, skipping all data. Could you please give me a method to solve that？ ![1687763877753](https://private-user-images.githubusercontent.com/130674437/248714055-08531d8f-5873-45ce-8046-000e47df06e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTY5NTAsIm5iZiI6MTcxODE5NjY1MCwicGF0aCI6Ii8xMzA2NzQ0MzcvMjQ4NzE0MDU1LTA4NTMxZDhmLTU4NzMtNDVjZS04MDQ2LTAwMGU0N2RmMDZlNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxMjUwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2I0YjJjZjQ1OWI0NTE4NzlhNDhmMjgwMDNhNTZhYjc0MTA5NDhjYThlZmM5MjZjOGU1NWNmZDdiMWRiYmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YmJBbSfHAs-r7dgGrxffWLRXNyztG2Qq2AkbINfW0Cs)

Have you solved this problem? I met this error too! @zhangxiaofan-star
