### ISSUE TITLE
Questions about the correctness of the codes

### ISSUE THREAD

**Issue by sea2023time** [zaixizhang/FLAG#9]
Hi Zaixi,

After spending a long time (more than 1 month) reproducing the results reported in your paper, I find that some parts of the codes may be unreasonable.    
I will not list every unreasonable one here, but show one example:    
https://github.com/zaixizhang/FLAG/blob/main/utils/chemutils.py#L40    
The normalization is commented out. But it is obviously necessary here because the direction vector of the rotation axis must be a unit vector. This makes the function not actually physical rotation at all.   

After all, the reported performance of this paper is still not reproduced.   
Could you provide more information?

**Comment by zaixizhang** [comment]
Hi,

Thanks for your feedback! In our experiments, we observed that the normalization has little influence on the final generation quality. For the clarity of the code, I have uncommented the normalization. Thanks!

**Comment by sea2023time** [comment]
Hi,  

Thanks for your reply.  
We have different observations from yours and now we suspect the results reported in the paper.  
Besides, with the normalization commented out or not, the performances are both far from the reported.   
There are several logical mistakes in your codes, which I think you must be aware of, and we wonder how your work achieves the results reported in the paper.   

Could you please provide convincing evidence for the results in the paper and your observation mentioned above?

**Comment by sea2023time** [comment]
Hi,   

Leaving the code of normalization commented out as we mentioned above leads to extremely unrealistic conformation, which is obviously different from your observation. And uncommenting it leads to other issues. You must be aware of this.   

If you are sure about the results reported in the paper, please provide complete codes for both training and testing to support your claim.

**Comment by zaixizhang** [comment]
Hi,

I am interested in your results and could you provide more details so that I can help? We have done extensive experiment evaluations. But for the reasons of other projects and intellectual property, we can now provide the preliminary version. We will release the latest version soon.
